## AMCL Parameters
## http://wiki.ros.org/amcl#Parameters
## Using a ChatGPT generated template. Verify carefully.

# update_min_d: 0.2               # Minimum distance (in meters) that the robot has to move before AMCL is updated
# update_min_a: 0.2               # Minimum rotation (in radians) that the robot has to rotate before AMCL is updated
# alpha1: 0.2                     # Odometry noise parameter
# alpha2: 0.2                     # Odometry noise parameter
# alpha3: 0.2                     # Odometry noise parameter
# alpha4: 0.2                     # Odometry noise parameter
laser_max_range: 30.0           # Maximum laser range (meters)
laser_min_range: 0.12           # Minimum laser range (meters)
max_particles: 5000             # Maximum number of particles to use in AMCL
min_particles: 500              # Minimum number of particles
initial_pose_x: -6.5            # Initial x position (in meters)
initial_pose_y: 0.0             # Initial y position (in meters)
initial_pose_a: 0.0             # Initial yaw angle (in radians)
resample_interval: 2            # The interval at which to resample particles
transform_tolerance: 1.0        # Time tolerance for the transform from odom to base_link frame
# odom_frame_id: odom             # Frame of reference for the robot's odometry
odom_model_type: omni-corrected # diff-corrected
# base_frame_id: base_link        # Frame of reference for the robot's base
laser_model_type: likelihood_field          # Type of laser sensor model (beam, likelihood_field_prob if enabled)
use_map_topic: true             # Whether to subscribe to a map topic
first_map_only: true            ## When set to true, AMCL will only use the first map it subscribes to
selective_resampling: true ## When set to true, will reduce the resampling rate when not needed and help avoid particle deprivation
# kld_err: 0.01                   # KLD error threshold for particle filter
# kld_z: 0.99                     # KLD z value for particle filter
# sigma_hit: 0.2                  # Sigma value for sensor hit model
# lambda_short: 0.1               # Lambda value for short laser readings
# z_hit: 0.95                     # Hit model parameter
# z_rand: 0.05                    # Random model parameter
# z_max: 0.05                     # Maximum laser range

## Topic to subscribe to for LaserScan data (usually from a sensor like a LIDAR)
scan_topic: /scan

## Map topic, which AMCL uses for localization
map_topic: /map

## For multi-robot setups, you can define namespaces
namespace: ""