local_costmap:
   global_frame: odom
   # robot_base_frame: robot_footprint  ## nov05
   robot_base_frame: base_link          ## nov05
   update_frequency: 5.0
   publish_frequency: 2.0 # 5.0
   width: 10.0
   height: 10.0
   origin_x: -5.0  ## Half of the width/height for centering around the robot
   origin_y: -5.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}  ## ROS2, "nav2_costmap_2d::StaticLayer"
      - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
      - {name: inflation_layer, type: "costmap_2d::InflationLayer"}
