local_costmap:
   global_frame: odom
   # robot_base_frame: robot_footprint  ## nov05
   robot_base_frame: base_link          ## nov05
   update_frequency: 5.0
   publish_frequency: 5.0
   width: 10.0
   height: 10.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   plugins: ["obstacle_layer", "inflation_layer"]
   obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
   inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"
